name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Configure git user name
        uses: fregante/setup-git-user@v1

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install project
        run: npm install .

      - name: Test and Lint
        run: npm run test

      - name: Build
        run: npm run build-prod

      - name: Deploy to gh-pages
        run: npm run publish-cmd
